name: Deploy to GitHub Pages

on:
  push:
    branches: [master]  # This workflow triggers only when pushing to the "master" branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout the repository content

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Set the Node.js version to 20

      - name: Enable Corepack
        run: corepack enable  # Enable Corepack to use Yarn v4

      - name: Install Yarn 4
        run: corepack prepare yarn@4.9.1 --activate  # Install and activate Yarn 4.9.1

      - name: Install dependencies
        run: yarn  # Install project dependencies using Yarn

      - name: Build the project
        run: yarn build  # Build the app using Vite

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Action to deploy to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use a Personal Access Token (PAT) named GH_TOKEN
          publish_dir: ./dist  # The directory where Vite outputs the build files
          user_name: 'github-actions'  # GitHub user name for the deploy commit
          user_email: 'github-actions@users.noreply.github.com'  # GitHub user email for the commit
